services:
  backend:
    build: .
    container_name: ayee-portal-backend
    ports:
      - "${AYEE_PORTAL_SERVER_PORT:-8080}:8080"
    environment:
      - PG_DB_HOST=${PG_DB_HOST}
      - PG_DB_PORT=${PG_DB_PORT}
      - PG_DB_USER=${PG_DB_USER}
      - PG_DB_PASSWORD=${PG_DB_PASSWORD}
      - PG_AYEE_PORTAL_DB_NAME=${PG_AYEE_PORTAL_DB_NAME}
      - AYEE_PORTAL_SERVER_PORT=8080
    restart: always
